### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by keisukesaito7** [keisukesaito7/furima-30471#9]
### 自身のフリマアプリのURL
https://furima-30471.herokuapp.com/

### Basic認証のIDとパスワード
- id : admin
- password : 1669

### 出品者用のメールアドレスとパスワード
- email : sample@test.com
- password : sample0

### 購入者用のメールアドレスとパスワード
- email : another@test.com
- password : another0

### 購入用カードの番号・期限・セキュリティコード
- number : 4242424242424242
- MM/YY : 10/33
- CVC : 123

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by keisukesaito7** [comment]
ご確認ありがとうございます！
皆さまには本当にお世話になりました。ありがとうございました！
